#!/bin/sh

# This is device-hacks, a placeholder file for device-specific "hacks" or commands
# that has to be run on the GNU/Linux side at boot.


# To use, overlay a shell script to this file. By default, it'll run after
# lxc-android-config.service (the container), but one can override the behavior
# by overlaying device-hacks.service.d/device-specific-settings.conf or the
# device-hacks.service file itself.

# see /usr/lib/lxc-android-config/lxc-android-ready
# FIXME verify that this is needed/not needed
while [ ! -e /dev/socket/property_service ]; do sleep 0.1; done
while [ -z "$(getprop ro.build.version.sdk)" ]; do sleep 0.1; done

# evaluating a kernel side solution of this, disabled now
#bash /usr/libexec/lxc-android-config/device-hacks.d/fingerprint_reader_fix.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/systemd_rcu_stall.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/local-image-waydroid.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/zram.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/swap.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/flashlight_permission.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/waydroid_register_gps.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/wait_for_lighthal.sh

bash /usr/libexec/lxc-android-config/device-hacks.d/hide_hwc_lib.sh

echo "=== lxc android is ready and hacks have been applied ===" > /dev/kmsg
#bash /usr/libexec/lxc-android-config/device-hacks.d/debug_ssh.sh
